### PR TITLE
Getting started guide

### PR DESCRIPTION
**Pull request by kotp**
OK, we can discuss and work on it here.

### CODE REVIEW

**Comment by rpottsoh** [comment]
I like this....

**Comment by kotp** [comment]
We have, when we were transitioning from your use of the GUI tool to the command line git.  But it has definitely been a while.

**Comment by kotp** [comment]
Next step is to remove the manual numbering for headers.

**Comment by rpottsoh** [comment]
This looks great!
The TOC should start at the beginning of a new page.  Also, I don't know if it is Acrobat or the PDF, but all the TOC entries out outlined in red.  I have not found a setting to in Acrobat to affect this look.

image

**Comment by kotp** [comment]
That is display, not sure that we will fix that at the moment, until the document header levels are fixed... which is

*The Next Step*

**Comment by rpottsoh** [comment]
Anything that is a link is outlined.  Will keep looking for a setting.

**Comment by rpottsoh** [comment]
Corrected section leveling towards end of document

**Comment by rpottsoh** [comment]
I don't think I want PDF as final result.  This is meant to be available or delivered, to new students of the Delphi track.  This document is intended to take care of exercism/delphi#2

**Comment by rpottsoh** [comment]
** Background was missing a eol before starting actual text for the section

**Comment by kotp** [comment]
Notice the page break directive that survives... not great.

**Comment by rpottsoh** [comment]
I noticed that, otherwise looks pretty good.

**Comment by rpottsoh** [comment]
MD looks ok, but toc links are broken.  Not sure how to fix them.

**Comment by rpottsoh** [comment]
@kotp I've lost my train of thought on this...  The PDF version you can produce looks pretty good.  The HTML ans MD versions look good too.  My original goal was to deliver an html stub that would link back to a MD version of the file on GitHub.  That way as changes are made to the document the students will always have the latest available....  The MD version looks fine, however the TOC links are broken.  The only way I know to fix them is to by-hand go through and fix each one :-1: .  I am wondering if, for now it would be better to abandon having a live TOC in order to finish this and merge.  This [TOC] is something that I could pursue later.

Also, I just committed an update to the ORG file so new conversion will need to be made.

**Comment by rpottsoh** [comment]
Generally this looks like a step in the right direction.  You used REGEX to manipulate the MD file?

The root level elements render as lowercase roman numerals instead of as numbers.  Indentation of the TOC looks OK otherwise.  In the body a space needs to be inserted between each section number and its associated heading.

For example, presently
```
### 4.1Background
```
should be
```
### 4.1 Background
```
Also, in the body root level headings are not numbered.  Instead they are underlined.

```
Introduction
----------------------------------------------------
```
instead of
```
### 4.0 Introduction
```

Another quirk, that has been here for awhile, in the body, the headings are all links back to themselves.  The effect when clicking is to relocate the document so that heading starts at the top of the browser window.

**Pull request closed without merging**
